### PR TITLE
Query string support

### PR DESCRIPTION
**Pull request by simenbrekken**
This PR will eventually feature query string support.

### CODE REVIEW

**Comment by andreypopp** [comment]
Nice!

We should decide where to pass querystring to and if we should parse it (personally I think we should parse it with some minimal querystring parser (qs)?).

Currently we pass params extracted from URL segment to a corresponding view/subview. What about querystring? Should we pass it 1) to view only or 2) to view and to every subview?

**Comment by simenbrekken** [comment]
I think we should parse it and make it available as `query` in the view and subviews as it may change the behavior of both main and sub views.

In addition we could encode query passed to navigation:

`this.navigate('/products', {query: {foo: 'bar'}})`

**Comment by simenbrekken** [comment]
On a side note it would be nice to be able to do:

`this.navigate({to: 'products/create', parent: 'foo'})`

**Comment by andreypopp** [comment]
Ok, that sounds reasonable.

What does `this.navigate({to: 'products/create', parent: 'foo'})` mean?

**Comment by simenbrekken** [comment]
Navigates to the route named `create`, a child of `products` and passes prop `parent` with value `foo`

**Comment by andreypopp** [comment]
Ah, ok, routing by route reference. Yes we should add this. Created an issue #28

**Comment by simenbrekken** [comment]
@andreypopp You can merge this in now to get just the basics, and we can just reopen it or create a new PR when the final functionality lands.

**Comment by andreypopp** [comment]
Thanks!

**Comment by simenbrekken** [comment]
@andreypopp Doesn't look like query is merged into props when creating view promises.

**Comment by andreypopp** [comment]
@sbrekken right, fixed in 0.1.1

**Comment by simenbrekken** [comment]
@andreypopp Also I feel it's a bit inconvenient that `query` is null when no query string parameters are present. An empty object would avoid having to place null checks all over the place:

```
var id = Number(params.query.id)
```

instead of:

```
var id = params.query && Number(params.query)
```

**Comment by andreypopp** [comment]
@sbrekken fixed in 0.1.2

**Pull request merged**
